version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: microservices_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: microservices
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    command: ["./auth"]
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=microservices
      - DB_PARAMS=charset=utf8mb4&parseTime=True&loc=Local
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=24h
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
    networks:
      - microservices_network
    restart: on-failure

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    command: ["./user"]
    ports:
      - "8082:8082"
      - "9092:9092"
    depends_on:
      mysql:
        condition: service_healthy
      auth-service:
        condition: service_started
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=microservices
      - DB_PARAMS=charset=utf8mb4&parseTime=True&loc=Local
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=24h
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
    networks:
      - microservices_network
    restart: on-failure

networks:
  microservices_network:
    driver: bridge

volumes:
  mysql_data:
