apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base resources
resources:
  - ../../base

# Set namespace for all resources
namespace: microservices-staging

# Add staging-specific ConfigMap
configMapGenerator:
  - name: environment-overlay
    behavior: create
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
      - USE_MOCK_SERVICES=false
      - BYPASS_AUTH=false

# Override ConfigMaps
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: auth-service-config
    data:
      LOG_LEVEL: "info"
      ENVIRONMENT: "staging"
      USE_MOCK_SERVICES: "false"
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: user-service-config
    data:
      LOG_LEVEL: "info"
      ENVIRONMENT: "staging"
      USE_MOCK_SERVICES: "false"

# Override Ingress host for staging
patches:
  - target:
      kind: Ingress
      name: auth-service-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.staging.your-domain.com
  - target:
      kind: Ingress
      name: user-service-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.staging.your-domain.com
